RestoranUygulaması/RestoranUygulaması.UI/Models/ErrorViewModel.cs
namespace RestoranUygulaması.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RestoranUygulaması/RestoranUygulaması.UI/Models/GirisYapViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RestoranUygulaması.UI.Models
{
    public class GirisYapViewModel
    {
        [Required]
        public string Ad { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
    }
}

RestoranUygulaması/RestoranUygulaması.UI/Models/KayitOlViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RestoranUygulaması.UI.Models
{
    public class KayitOlViewModel
    {
        [Required]
        [MinLength(4)]
        [MaxLength(20)]
        public string Ad { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [MinLength(4)]
        [MaxLength(30)]
        public string Sifre { get; set; }
    }
}

RestoranUygulaması/RestoranUygulaması.UI/Models/SepeteEkleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RestoranUygulaması.UI.Models
{
    public class SiparisOlusturViewModel
    {
        [Required]
        public string Ad { get; set; }

        [Required]
        public string Fiyat { get; set; }

        [Required]
        public Guid KullaniciId { get; set; }
    }
}

RestoranUygulaması/RestoranUygulaması.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RestoranUygulaması.UI.Models;
using System.Diagnostics;

namespace RestoranUygulaması.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RestoranUygulaması/RestoranUygulaması.UI/Controllers/KullaniciController.cs
using Microsoft.AspNetCore.Mvc;
using RestoranUygulaması.Business;
using RestoranUygulaması.Entities;
using RestoranUygulaması.UI.Models;

namespace RestoranUygulaması.UI.Controllers
{
    public class KullaniciController : Controller
    {
        private readonly IKullaniciServisi _kullaniciServisi;

        // IKullaniciServisi'nin constructor ile enjekte edilmesi
        public KullaniciController(IKullaniciServisi kullaniciServisi)
        {
            _kullaniciServisi = kullaniciServisi;
        }

        public IActionResult GirisYap()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GirisYap(GirisYapViewModel model)
        {
            if (!ModelState.IsValid) { return View(model); }

            Kullanici kullanici = _kullaniciServisi.GirisYap(model.Ad, model.Sifre);

            if (kullanici != null)
            {
                // Kullanıcı Id saklıyoruz
                HttpContext.Session.SetString("KullaniciId", kullanici.Id.ToString());

                return View("~/Views/Siparis/Menu.cshtml");
            }

            return View("~/Views/Home/Index.cshtml");
        }

        public IActionResult KayitOl()
        {
            return View();
        }

        [HttpPost]
        public IActionResult KayitOl(KayitOlViewModel model)
        {
            if (!ModelState.IsValid) { return View(model); }

            Kullanici kullanici = new Kullanici();
            kullanici.Ad = model.Ad;
            kullanici.Sifre = model.Sifre;

            _kullaniciServisi.KayitOl(kullanici);

            return View("~/Views/Home/Index.cshtml");
        }

        public IActionResult CikisYap()
        {
            HttpContext.Session.SetString("KullaniciId", "logout");
            return View("~/Views/Home/Index.cshtml");
        }

    }
}

RestoranUygulaması/RestoranUygulaması.UI/Controllers/SiparisController.cs
using Microsoft.AspNetCore.Mvc;
using RestoranUygulaması.Business;
using RestoranUygulaması.Entities;
using RestoranUygulaması.UI.Models;

namespace RestoranUygulaması.UI.Controllers
{
    public class SiparisController : Controller
    {
        private readonly IKullaniciServisi _kullaniciServisi;
        private readonly ISiparisServisi _siparisServisi;

        public SiparisController(IKullaniciServisi kullaniciServisi, ISiparisServisi siparisServisi)
        {
            _kullaniciServisi = kullaniciServisi;
            _siparisServisi = siparisServisi;
        }

        public IActionResult Menu()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SiparisEt(string Ad, decimal Fiyat)
        {
            Yemek yemek = new Yemek();
            yemek.Ad = Ad;
            yemek.Fiyat = Fiyat;
            
            _siparisServisi.SiparisOlustur(Guid.Parse(HttpContext.Session.GetString("KullaniciId")), yemek);

            ViewBag.Message = "Siparişiniz Alınmıştır";
            return View("~/Views/Siparis/Menu.cshtml");
        }

        public IActionResult Siparisler()
        {
            List<Siparis> siparisler = _siparisServisi.KullaniciSiparisleri(Guid.Parse(HttpContext.Session.GetString("KullaniciId")));
            return View(siparisler);
        }

        [HttpPost]
        public IActionResult SiparisİptalEt(int siparisId)
        {
            _siparisServisi.Siparisİptal(siparisId);
            List<Siparis> siparisler = _siparisServisi.KullaniciSiparisleri(Guid.Parse(HttpContext.Session.GetString("KullaniciId")));
            return View("~/Views/Siparis/Siparisler.cshtml", siparisler);
        }
    }
}

RestoranUygulaması/RestoranUygulaması.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Restoran Uygulamasına Hoşgeldiniz</h1>
    <a class="nav-link text-dark" asp-area="" asp-controller="Kullanici" asp-action="GirisYap">Buraya Tıklayarak Giriş Yapabilirsiniz</a>
</div>

RestoranUygulaması/RestoranUygulaması.UI/Views/Kullanici/GirisYap.cshtml
@model RestoranUygulaması.UI.Models.GirisYapViewModel

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

        <form asp-controller="Kullanici" asp-action="GirisYap" method="post" class="mt-3">

            <h1 class="mt-3">Login</h1>

            <!-- <div asp-validation-summary="All" class="text-danger"></div> -->

            <div class="mt-3">
                <label asp-for="Ad" class="form-label">Ad</label>
                <input asp-for="Ad" type="text" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>

            <div class="mt-3">
                <label asp-for="Sifre" class="form-label">Sifre</label>
                <input asp-for="Sifre" type="password" class="form-control" />
                <span asp-validation-for="Sifre" class="text-danger"></span>
            </div>

            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>

        </form>

        <div class="mt-3">
            <a asp-controller="Front" asp-action="Register">Did you not register yet?</a>
        </div>

    </div>
    <div class="col-md-4"></div>
</div>

RestoranUygulaması/RestoranUygulaması.UI/Views/Kullanici/KayitOl.cshtml
@model RestoranUygulaması.UI.Models.KayitOlViewModel


<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

        <h1 class="mt-3">Register</h1>

        <form asp-controller="Kullanici" asp-action="KayitOl" method="post" class="mt-3">

            <div class="mt-3">
                <label asp-for="Ad" class="form-label">Ad</label>
                <input asp-for="Ad" type="text" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>

            <div class="mt-3">
                <label asp-for="Sifre" class="form-label">Sifre</label>
                <input asp-for="Sifre" type="password" class="form-control" />
                <span asp-validation-for="Sifre" class="text-danger"></span>
            </div>

            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Kayit Ol</button>
            </div>

        </form>

    </div>
    <div class="col-md-4"></div>
</div>

RestoranUygulaması/RestoranUygulaması.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestoranUygulaması.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestoranUygulaması.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestoranUygulaması.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-end">
                        @if (HttpContextAccessor.HttpContext.Session.GetString("KullaniciId") != "logout" && HttpContextAccessor.HttpContext.Session.GetString("KullaniciId") != null)
                        { 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Siparis" asp-action="Menu">Menü</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Siparis" asp-action="Siparisler">Siparişler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kullanici" asp-action="CikisYap">Çıkış Yap</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RestoranUygulaması/RestoranUygulaması.UI/Views/Siparis/Menu.cshtml
@model RestoranUygulaması.UI.Models.SiparisOlusturViewModel

<h1>Menü</h1>
<br />

@if (ViewBag.Message != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Siparişiniz alınmıştır!</strong> Afiyet olsun.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="card">
    <div class="card-body">
        <table class="table table-hover align-middle">
            <thead>
                <tr scope="col">
                    <td>#</td>
                    <td>Ad</td>
                    <td>Fiyat</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <tr scop="row">
                    <td style="width: 200px"><img src="@Url.Content("~/img/hamburger.jpg")" width="180" /></td>
                    <td>Hamburger</td>
                    <td>150</td>
                    <td>
                        <form asp-controller="Siparis" asp-action="SiparisEt" method="post" class="mt-3">

                            <input asp-for="Ad" value="Hamburger" hidden />
                            <input asp-for="Fiyat" value="150" hidden />

                            <div class="mt-3">
                                <button type="submit" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">Sipariş Et</button>
                            </div>

                        </form>
                    </td>
                </tr>
                <tr scop="row">
                    <td style="width: 200px"><img src="@Url.Content("~/img/pizza.jpg")" width="180" /></td>
                    <td>Pizza</td>
                    <td>200</td>
                    <td>
                        <form asp-controller="Siparis" asp-action="SiparisEt" method="post" class="mt-3">

                            <input asp-for="Ad" value="Pizza" hidden />
                            <input asp-for="Fiyat" value="200" hidden />

                            <div class="mt-3">
                                <button type="submit" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">Sipariş Et</button>
                            </div>

                        </form>
                    </td>
                </tr>
                <tr scop="row">
                    <td style="width: 200px"><img src="@Url.Content("~/img/sandwich.jpg")" width="180" /></td>
                    <td>Sandiviç</td>
                    <td>100</td>
                    <td>
                        <form asp-controller="Siparis" asp-action="SiparisEt" method="post" class="mt-3">

                            <input asp-for="Ad" value="Sandiviç" hidden/>
                            <input asp-for="Fiyat" value="100" hidden />

                            <div class="mt-3">
                                <button type="submit" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">Sipariş Et</button>
                            </div>

                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

RestoranUygulaması/RestoranUygulaması.UI/Views/Siparis/Siparisler.cshtml
@model List<RestoranUygulaması.Entities.Siparis>
@{
    decimal toplamTutar = 0;
}
<h1>Siparişler</h1>
<br />

<div class="card">
    <div class="card-body">
        <table class="table table-hover align-middle">
            <thead>
                <tr scope="col">
                    <td>#</td>
                    <td>Ad</td>
                    <td>Fiyat</td>
                    <td>Sipariş Tarihi</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                
                @foreach (var siparis in Model)
                {
                    var img = "";
                    @if (@siparis.SiparisEdilenYemek.Ad == "Hamburger")
                    {
                        img = "~/img/hamburger.jpg";
                    }
                    @if (@siparis.SiparisEdilenYemek.Ad == "Pizza")
                    {
                        img = "~/img/pizza.jpg";
                    }
                    @if (@siparis.SiparisEdilenYemek.Ad == "Sandiviç")
                    {
                        img = "~/img/sandwich.jpg";
                    }

                    @if(siparis.IptalDurumu == false)
                    {
                        toplamTutar += siparis.SiparisEdilenYemek.Fiyat;
                    }
                    
                    <tr>
                        <td><img src="@Url.Content(img)" width="180" /></td>
                        <td>@siparis.SiparisEdilenYemek.Ad</td>
                        <td>@siparis.SiparisEdilenYemek.Fiyat</td>
                        <td>@siparis.SiparisTarihi.ToString("dd/MM/yyyy")</td>

                        <td>
                            @if (@siparis.IptalDurumu == false)
                            {
                                <form asp-controller="Siparis" asp-action="SiparisİptalEt" method="post" class="mt-3">

                                    <input name="siparisId" value="@siparis.Id" hidden />

                                    <div class="mt-3">
                                        <button type="submit" class="btn btn-danger">Sipariş İptal Et</button>
                                    </div>

                                </form>
                            }
                            else
                            {
                                <p>Sipariş İptal Edilmiş</p>
                            }
                        </td>

                    </tr>
                }
            </tbody>
        </table>

        <div>
            Siparişler Toplam Tutarı: @toplamTutar.ToString("C")
        </div>
    </div>
</div>